config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :accounts, only: [:index, :show]
  get 'refresh_bike_index', to: 'accounts#refresh_bike_index_credentials'

  authenticate :user, lambda { |u| u.superuser? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'serial_searches#index'

  resources :log_lines, only: [:create]
  resources :ip_addresses, only: [:index, :show, :edit, :update]
  resources :serial_searches, only: [:index, :show]
  resources :graphs, only: [:index] do
    collection do
      get 'source_type'
      get 'uniquely_created_entries'
    end
  end
end

app/models/serial_search.rb
class SerialSearch < ApplicationRecord
  validates_presence_of :serial
  validates_uniqueness_of :serial

  has_many :log_lines
  has_many :ip_addresses, through: :log_lines
  has_many :bike_serial_searches
  has_many :bikes, -> { distinct }, through: :bike_serial_searches

  before_save :sanitize_serial

  def valid_serial_search_for_bike_creation?
    searched_bike_index_at.nil? || !within_min_request_time
  end

  def within_min_request_time
    (searched_bike_index_at <= Time.now) && (searched_bike_index_at >= SerialSearch.min_request_time)
  end

  def self.sufficient_length
    4
  end

  def self.min_request_time
    8.hours.ago
  end

  def self.text_search(query)
    if query.present?
      where('serial % ?', query)
    else
      all
    end
  end

  def sanitize_serial
    self.serial = serial.strip.upcase
  end
end

app/controllers/serial_searches_controller.rb
class SerialSearchesController < ApplicationController
  helper_method :sort_column, :sort_direction
  skip_before_action :ensure_superuser, only: [:index]
  before_action :ensure_user, only: [:index]

  def index
    if current_user.superuser?
      @title = 'Serial Searches'
      per_page = params[:per_page] || 50
      page = params[:page] || 1

      @serial_searches_count = SerialSearch.count
      @ip_addresses_count = IpAddress.count

      @serial_searches = SerialSearch.text_search(params[:query]).order(sort_column + ' ' + sort_direction).page(page).per(per_page)

      render 'superuser'
    else
      render 'index'
    end
  end

  def show
    @serial_search = SerialSearch.find(params[:id])
    @title = "Serial Searches for #{@serial_search.serial}"
  end

  private

  def sort_column
    SerialSearch.column_names.include?(params[:sort]) ? params[:sort] : 'serial'
  end

  def sort_direction
    %w(asc desc).include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/views/serial_searches/index.html.haml
- @user = current_user
= render '/layouts/user_view'

app/views/serial_searches/show.html.haml
.container-fluid
  %header.info-header
    %h4
      = pluralize(@serial_search.log_lines.count, 'Log Line')
      for
      %em
        = @serial_search.serial

  %table.table.table-striped.table-bordered.header-sortable
    %thead
      %tr
        %th IP Address
        %th Entry Data
        %th Request At
    %tbody
      - @serial_search.log_lines.each do |log|
        %tr
          %td
            - if log.ip_address.name.present?
              = link_to log.ip_address.name, ip_address_path(log.ip_address.id)
            - else
              = link_to log.ip_address.address, ip_address_path(log.ip_address.id)
            %small.ip-address-location
              = log.ip_address.location
              - if log.ip_address.notes.present?
                %a{ href: "#show_notes#{log.id}", class: 'float-right', data: { toggle: 'collapse' } }
                  Notes
                .collapse{ id: "show_notes#{log.id}" }
                  = log.ip_address.notes
          %td
            %pre
              = JSON.pretty_generate(log.present_entry_data)
            %small
              %a{ href: "#expanded_log_params_#{log.id}",  data: { toggle: 'collapse' }, 'aria-expanded' => 'false', 'aria-controls' => 'collapseExample' }
                All Parameters
            .collapse{ id: "expanded_log_params_#{log.id}" }
              %pre
                = JSON.pretty_generate(log.entry)
          %td
            = l log.request_at, format: :log_request_time

app/views/serial_searches/superuser.html.haml
.container-fluid
  %header.info-header
    %h4
      = @serial_searches_count
      Serial Searches from
      = @ip_addresses_count
      unique IP Addresses

    .form-inline
      = form_tag serial_searches_path, method: :get
      %p
        = text_field_tag :query, params[:query], class: 'form-control',
          placeholder: 'Serial Number'
        = submit_tag 'Search', name: nil, class: 'btn btn-primary'

  %table.table.table-striped.table-bordered.header-sortable
    %thead
      %tr
        %th
          = sortable 'serial'
        %th
          = sortable 'log_lines_count', 'Number of Searches'
        %th
          = sortable 'last_request_at', 'Most Recent Search'
    %tbody
      - @serial_searches.each do |serial_search|
        %tr
          %td
            = link_to serial_search.serial, serial_search_path(serial_search)
          %td
            = serial_search.log_lines_count
          %td
            = l serial_search.last_request_at, format: :log_request_time

  = paginate @serial_searches