config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :accounts, only: [:index, :show]
  get 'refresh_bike_index', to: 'accounts#refresh_bike_index_credentials'

  authenticate :user, lambda { |u| u.superuser? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'serial_searches#index'

  resources :log_lines, only: [:create]
  resources :ip_addresses, only: [:index, :show, :edit, :update]
  resources :serial_searches, only: [:index, :show]
  resources :graphs, only: [:index] do
    collection do
      get 'source_type'
      get 'uniquely_created_entries'
    end
  end
end

app/controllers/ip_addresses_controller.rb
class IpAddressesController < ApplicationController
  helper_method :sort_column, :sort_direction

  before_action :find_ip_address, except: [:index]

  def index
    @title = 'IP Addresses'
    per_page = params[:per_page] || 50
    page = params[:page] || 1
    @serial_searches_count = SerialSearch.count
    @ip_addresses_count = IpAddress.count
    @ip_addresses = IpAddress.order(sort_column + ' ' + sort_direction).page(page).per(per_page)
  end

  def show
    @title = "Searches from #{@ip_address.address}"
  end

  def edit
    @title = "Edit #{@ip_address.address}"
  end

  def update
    if @ip_address.update_attributes(ip_params)
      @ip_address.log_lines.each do |log_line|
        log_line.update_attribute(:inspector_request, log_line.inspector_request?)
      end
      redirect_to ip_address_path(@ip_address)
    else
      render :edit
    end
  end

  private

  def ip_params
    params.require(:ip_address).permit(:name, :notes, :started_being_inspector_at, :stopped_being_inspector_at)
  end

  def find_ip_address
    @ip_address = IpAddress.find(params[:id])
  end

  def sort_column
    IpAddress.column_names.include?(params[:sort]) ? params[:sort] : 'address'
  end

  def sort_direction
    %w(asc desc).include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/views/ip_addresses/edit.html.haml
.container-fluid
  %header.info-header
    .h4
      Edit
      %em
        = @ip_address.address
    %small
      = @ip_address.location
  %p
    Associated with
    = pluralize(@ip_address.log_lines.count, 'Log Line')

  = form_for @ip_address do |f|
    .form-check
      %label.form-check-label
        %input.form-check-input#has-been-inspector-checkbox{ type: 'checkbox', checked: @ip_address.been_inspector? }
        Has Been Inspector

    .collapse#expand-edit-inspector-time{ class: ('in' if @ip_address.been_inspector?) }
      .form-group.row
        = f.label :started_being_inspector_at, class: 'col-xs-2 col-form-label inspector-form'
        = f.datetime_local_field :started_being_inspector_at

      .form-group.row.inspector-form
        = f.label :stopped_being_inspector_at, class: 'col-xs-2 col-form-label inspector-form'
        = f.datetime_local_field :stopped_being_inspector_at

    .form-group.row
      = f.label :name, class: 'col-xs-2 col-form-label'
      = f.text_field :name, class: 'form-control col-xs-2'

    .form-group.row
      = f.label :notes, class: 'col-xs-2 col-form-label'
      = f.text_area :notes, class: 'form-control col-xs-3'

    .form-group
      = f.submit class: 'btn btn-success'

:javascript
  $(document).ready(function() {
    $('#has-been-inspector-checkbox').change(function(){
      if ($('#has-been-inspector-checkbox').prop('checked')){
        $('#expand-edit-inspector-time').collapse('show')
      } else {
        $('#expand-edit-inspector-time').collapse('hide')
        $('#expand-edit-inspector-time input').val('')
      }
    });
  });

app/views/ip_addresses/index.html.haml
.container-fluid
  %header.info-header
    %h4
      = @serial_searches_count
      Serial Searches from
      = @ip_addresses_count
      unique IP Addresses
  %table.table.table-striped.table-bordered.header-sortable
    %thead
      %tr
        %th
          = sortable 'address'
        %th Location
        %th
          = sortable 'log_lines_count', 'Number of Searches'
        %th
          = sortable 'last_request_at', 'Most Recent Search'
    %tbody
      - @ip_addresses.each do |ip_address|
        %tr
          %td
            - if ip_address.name.present?
              = link_to ip_address.name, ip_address_path(ip_address)
            - else
              = link_to ip_address.address, ip_address_path(ip_address)
            - if ip_address.notes.present?
              %small.float-right
                %a{ href: "#show_notes#{ip_address.id}", data: { toggle: 'collapse' } }
                  Notes
                .collapse{ id: "show_notes#{ip_address.id}" }
                  = ip_address.notes
          %td
            = ip_address.location
          %td
            = ip_address.log_lines_count
          %td
            - if ip_address.last_request_at.present?
              = l ip_address.last_request_at, format: :log_request_time

  = paginate @ip_addresses

app/views/ip_addresses/show.html.haml
.container-fluid
  %header.info-header
    %h4
      = pluralize(@ip_address.log_lines.count, 'Log Line')
      for
      %em
        = @ip_address.address
        - if @ip_address.name.present?
          (
          = @ip_address.name
          )
        from
        = @ip_address.location
        = link_to 'edit', edit_ip_address_path, class: 'btn btn-secondary float-right form-group'
    - if @ip_address.notes.present?
      %p
        = @ip_address.notes

  %table.table.table-striped.table-bordered
    %thead
      %tr
        %th Serial
        %th Entry Data
        %th Request At

    %tbody
      - @ip_address.log_lines.each do |log|
        %tr
          %td
            - if log.serial_search.present?
              = link_to log.entry['params']['serial'], serial_search_path(log.serial_search.id)
          %td
            %pre
              = JSON.pretty_generate(log.present_entry_data)
            %small
              %a{ href: "#expanded_log_params_#{log.id}",  data: { toggle: 'collapse' }, 'aria-expanded' => 'false', 'aria-controls' => 'collapseExample' }
                All Parameters
            .collapse{ id: "expanded_log_params_#{log.id}" }
              %pre
                = JSON.pretty_generate(log.entry)
          %td
            = l log.request_at, format: :log_request_time