config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :accounts, only: [:index, :show]
  get 'refresh_bike_index', to: 'accounts#refresh_bike_index_credentials'

  authenticate :user, lambda { |u| u.superuser? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'serial_searches#index'

  resources :log_lines, only: [:create]
  resources :ip_addresses, only: [:index, :show, :edit, :update]
  resources :serial_searches, only: [:index, :show]
  resources :graphs, only: [:index] do
    collection do
      get 'source_type'
      get 'uniquely_created_entries'
    end
  end
end

app/views/layouts/_about_modal.html.haml
.modal.fade#aboutModal{ 'tabindex': '-1', 'role': 'dialog', 'aria-labelledby': 'exampleModalLAbel?', 'aria-hidden': 'true' }
  .modal-dialog{ 'role': 'document'}
    .modal-content
      .modal-header
        %h5.modal-title.inline
          Serial Search Inspector
        %button.close{ 'type': 'close', 'data-dismiss': 'modal', 'aria-label': 'Close' }
          %span{ 'aria-hidden': true }
            &times;
      .modal-body
        %p
          The Serial Search Inspector is a new tool that allows Bike Index to monitor
          serial number searches on the registry. This allows us to see a little more
          into how people use the Bike Index and provides additional information to you.
        %p
          How it works: The Inspector functions in conjunction with Bike Index. When a
          serial number is searched for on the Bike Index, we create a log of that
          search and share it with the Inspector. The Inspector then, determined by the
          validity of the search, checks if that serial matches to a registered bike on
          the registry. If there is a match, we link that search and bike together.
          This lets you see when a bike registered to you is searched for.
        %p
          There are a few things to keep in mind regarding this information.
        %p
          First, it is possible, though unlikely, that two or more bikes could share a
          serial number or your bike could be matched with a partial serial number search.
          This would happen if two or more manufacturers happen to use the same serial number.
          What does this mean for you? Well, if this were the case, there may be serial
          number searches that were intended for a different bike and vice versa.
        %p
          Second, the location provided with the logged searches are rough and are based
          closest by city. This is hopefully intended to see if someone across the country
          is searching for you bike.
        %p
          We hope you enjoy this new tool and find it useful.

app/views/layouts/_navbar.html.haml
- if current_user.superuser?
  %nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
    %a.navbar-brand{ href: '#' }
      = image_tag 'logo.svg', class: 'logo d-inline-block align-top'
      = link_to 'Admin', root_path, class: 'navbar-brand'
    %button.navbar-toggler{ type: 'button',  'data-toggle': 'collapse', 'data-target': '#navbarSupportedContent' }
      %span.navbar-toggler-icon
    .collapse.navbar-collapse#navbarSupportedContent
      %ul.navbar-nav
        %li.nav-item
          = link_to 'Users', accounts_path, class: 'nav-link'
        %li.nav-item
          = link_to 'Serial Searches', serial_searches_path, class: 'nav-link'
        %li.nav-item
          = link_to 'IP Addresses', ip_addresses_path, class: 'nav-link'
        %li.nav-item
          = link_to 'Graphs', graphs_path, class: 'nav-link'
- else
  %nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
    %a.navbar-brand{ href: '#' }
      = image_tag 'logo.svg', class: 'logo d-inline-block align-t op'
      = link_to 'Bike Index: Serial Search Inspector', root_path, class: 'navbar-brand'
    %button.navbar-toggler{ type: 'button',  'data-toggle': 'collapse', 'data-target': '#navbarSupportedContent' }
      %span.navbar-toggler-icon
    .collapse.navbar-collapse#navbarSupportedContent
      %ul.nav.navbar-nav
        %li.nav-item
          %a.nav-link{ href: '', 'data-toggle': 'modal', 'data-target': '#aboutModal' }
            About

app/views/layouts/_user_view.html.haml
.container-fluid
  %header.info-header
    %h4
      Welcome, #{@user.email}
    - @user.bikes.each do |bike|
      .card
        .card-block
          %h5.card-title
            #{bike.title} - #{bike.serial}

          %a.card-link{ href: "https://bikeindex.org/bikes/#{bike.bike_index_id}" }
            View on BikeIndex

          - if bike.serial_searches.empty?
            %p.card-text
              There are no recorded searches for this serial number
          - else
            - bike.serial_searches.each do |serial_search|
              %table.table.table-striped.table-bordered
                %thead
                  %tr
                    %th Serial Searched for
                    %th Time
                    %th Location
                  %tbody
                    - serial_search.log_lines.each do |log_line|
                      - next if log_line.inspector_request
                      %tr
                        %td
                          = log_line.entry['params']['serial']
                        %td
                          = l log_line.request_at, format: :log_request_time
                        %td
                          = log_line.ip_address.city

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = @title
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag '/favicon.ico'
  %body
    = render '/layouts/navbar'
    = render '/layouts/about_modal'

    - if notice.present?
      %p.notice.alert-info
        = notice
    - if alert.present?
      %p.alert.alert-danger
        = alert

    = yield

    %footer.footer
      .container
        = link_to 'Refresh Bike Index bikes', user_bike_index_omniauth_authorize_path
        %span.text-muted.float-right
          The Serial Search Inspector is an Open Source Project.
          View on
          = link_to 'Github', 'https://github.com/bikeindex/serial_search_inspector'