config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :accounts, only: [:index, :show]
  get 'refresh_bike_index', to: 'accounts#refresh_bike_index_credentials'

  authenticate :user, lambda { |u| u.superuser? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'serial_searches#index'

  resources :log_lines, only: [:create]
  resources :ip_addresses, only: [:index, :show, :edit, :update]
  resources :serial_searches, only: [:index, :show]
  resources :graphs, only: [:index] do
    collection do
      get 'source_type'
      get 'uniquely_created_entries'
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  helper_method :sort_column, :sort_direction
  skip_before_action :ensure_superuser, only: [:refresh_bike_index_credentials]
  before_action :ensure_user, only: [:refresh_bike_index_credentials]

  def index
    @users = User.all
    @user_count = User.count
  end

  def show
    @user = User.find(params[:id])
  end

  def refresh_bike_index_credentials
    session[:aso] = root_url
    redirect_to destroy_user_session_path(method: :delete)
  end

  private

  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : 'created_at'
  end

  def sort_direction
    %w(asc desc).include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/views/accounts/index.html.haml
.container-fluid
  %header.info-header
    %h4
      = @users_count
      users
  %table.table.table-striped.table-bordered.header-sortable
    %thead
      %tr
        %th
          = sortable 'email', 'email'
        %th
          = sortable 'created_at', 'Created (on inspector)'
        %th
          Bikes
    %tbody
      - @users.each do |user|
        %tr
          %td
            = link_to user.email, account_path(id: user.id)
          %td
            = l user.created_at, format: :date
          %td
            = user.bikes.count

app/views/accounts/show.html.haml
= render '/layouts/user_view'